name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-deploy:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          cache: yarn
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          git config --global user.email "2531535061@qq.com"   # 修改为你的Github邮箱地址
          git config --global user.name "Shake-Jarjane"        # 修改为你的Github用户名
          yarn install --frozen-lockfile
          yarn deploy
# docsearch
      - name: Get the content of docsearch.json as config
        id: algolia_config
        run: echo "::set-output name=config::$(cat docsearch.json | jq -r tostring)"

      - name: Run algolia/docsearch-scraper image
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}
        run: |
          docker run \
            --env APPLICATION_ID=${ALGOLIA_APP_ID} \
            --env API_KEY=${ALGOLIA_API_KEY} \
            --env "CONFIG=${CONFIG}" \
            algolia/docsearch-scraper
# search-engines-urls-push
      - name: search-engines-urls-push
        id: search-engines-urls-push
        uses: 3Alan/search-engines-urls-push@v0.2.3
        with:
          site: ${{ secrets.SITE }}
          sitemap: ${{ secrets.SITEMAP }}
          count: ${{ secrets.COUNT }}
          bing-token: ${{ secrets.BING_TOKEN }}
          baidu-token: ${{ secrets.BAIDU_TOKEN }}
          # google-client-email: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          # google-private-key: ${{ secrets.GOOGLE_PRIVATE_KEY }}